# Generated by Django 5.0.7 on 2024-07-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceApp', '0002_image_delete_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to='processed/'),
        ),
    ]
